### ISSUE TITLE
change aspect ratio of themes

### ISSUE THREAD

**Issue by ddbelyaev** [cab-1729/Pandoc-Themes#2]
Hi! First of all, great templates! :)

I've been trying to put
```md
---
aspectratio: 169
---
```

in my markdown file, but it seems to be overwritten by the theme file. What should I change in the tex file to achieve the desired aspect ratio? Thank you!

**Comment by cab-1729** [comment]
```aspectratio``` seems to be specific to beamer slides.
All the themes were modeled after themes available for Typora, hence they are meant to be as close to those as possible. As a result metadata is often ignored for sake of sticking to the theme. On top of that these themes were meant for articles, not beamer slides.

However, if one wishes to compile to beamer (using the ```-t beamer``` option for pandoc instead) and follow things like the aspect ratio the themes need to be changed in the following manner:

Replace ```\documentclass{article}``` (2nd line of each template file) with 

```latex
\documentclass[
$if(fontsize)$
  $fontsize$,
$endif$
$if(papersize)$
  $papersize$paper,
$endif$
$if(beamer)$
  ignorenonframetext,
$if(handout)$
  handout,
$endif$
$if(aspectratio)$
  aspectratio=$aspectratio$,
$endif$
$endif$
$for(classoption)$
  $classoption$$sep$,
$endfor$
]{$documentclass$}
```
which is line 11-30 of the output of ```pandoc -D beamer```.

I haven't tried it, but I think that would do it.

Does this solve your question?

**Comment by ddbelyaev** [comment]
yes, this turns out to be beamer feature, my apologies. in any case I've tried what you proposed, substituted line 2 of template and ran the following command with the output:
```
pandoc --pdf-engine=xelatex -f markdown -t pdf --template=drake-ayu.tex file.md > file.pdf
Error producing PDF.
! Misplaced \noalign.
\newpage ->\noalign
                    {\break }
l.552 \end{document}
```

I also tried option -t beamer, but it produced a file not opened by pdf viewer.

My goal is to be able to create pdfs, but with 16:9 aspect ratio, and it doesn't really matter if its beamer or not, would be cool though. Is there any fix for this?

**Comment by cab-1729** [comment]
I found out now that my solution won't work on the templates. The code for creating beamer slides is very different from the code that would create articles. If the templates were to be utilized for beamer slides, a lot of technical changes need to be made.

The file you obtained by using ```-t beamer``` could not be opened by a pdf reader because ```pandoc``` outputs a ```.tex``` file when the beamer option is used. In order to get a pdf, the pdf engine must be run directly on the file outputted by pandoc.

Since ```pandoc``` uses ```aspectratio``` as an option exclusively for beamer slides, I'm afraid there's no way for the templates to read the ```aspectratio``` metadata from the markdown files.
If you need to set the aspect ratio of the resulting pdfs, you'd have to directly set it the template files.
This needs to be done by modifying the
```latex
\usepackage[*]{geomtery}
```
line and providing the dimensions of the page in the optional parameters.
